### ISSUE TITLE
Dynamic slides break slider

### ISSUE THREAD

**Issue by markfswe** [Splidejs/svelte-splide#7]
### Checks

- [X] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to Svelte Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

0.2.1

### Description

I tried to reproduce issue in svelte repl but it doesn't seems to work. Have no idea why svelte-splide is not compatible with REPL.

So here is link to codesandbox.

### Reproduction Link

https://codesandbox.io/s/mystifying-wave-wxi3hh?file=/App.svelte

### Steps to Reproduce

Just asynchronously render some more slides. Slider is broken now.

### Expected Behaviour

Slider works as should.

**Comment by NaotoshiFujita** [comment]
You are updating `slides` in the parent `onMount` method but it does not update child components.

This does not work:
```svelte
onMount(() => {
  slides = [...slides, { test: 3 }, { test: 4 }, { test: 5 }];
});
```

But this will work:
```svelte
onMount(() => {
  setTimeout( () => {
    slides = [...slides, { test: 3 }, { test: 4 }, { test: 5 }];
  } );
});
```

If you are loading slides asynchronously by async await, they are processed like the second example.
